name: Deploy to COS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  SECRET_ID: ${{ secrets.QCLOUD_SECRET_ID }}
  SECRET_KEY: ${{ secrets.QCLOUD_SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 18.x
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
    - name: Replace version
      run: node deploy/version.cjs $GITHUB_SHA
    - name: Build Project
      run: yarn build
    - name: Install coscmd
      run: sudo pip install coscmd
    - name: Configure coscmd
      env:
        SECRET_ID: ${{ env.SECRET_ID }}
        SECRET_KEY: ${{ env.SECRET_KEY }}
        BUCKET: shuhole-web-1323995138
        REGION: ap-shanghai
      run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
    - name: Upload to COS
      run: cd ./dist && coscmd upload -rs --delete -f ./ / && cd ..
    - name: Refresh CDN
      run: node deploy/refresh.cjs ${{ env.SECRET_ID }} ${{ env.SECRET_KEY }}